spring:
  datasource:
    url: jdbc:mysql://localhost:3306/connectmoney?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

security:
  jwt:
    secret_key: "omar_secret_key_01097094971"
    expiration_time: 3600000
  client-credentials:
    max-number-of-attempts: 5
    lockout-duration-time: 300 #5 minutes
  rate-limit:
    capacity: 100
    refill-tokens: 10
    refill-duration: 60

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: moneyy
    key-store-type: PKCS12
    key-alias: connectmoney
  error:
   include-message: never
    include-stacktrace: never