spring:
  datasource:
    url: jdbc:mysql://localhost:3306/connectmoney?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

security:
  jwt:
    secret_key: "omar_secret_key_01097094971"
    expiration_time: 3600000
  client-credentials:
    max-number-of-attempts: 5
    lockout-duration-time: 300 #5 minutes
  rate-limit:
    capacity: 100
    refill-tokens: 10
    refill-duration: 60